# Generated by Django 6.0.4 on 2026-04-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
                ('Picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('ContactName', models.CharField(max_length=255)),
                ('ContactTitle', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Region', models.CharField(max_length=255)),
                ('PostalCode', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=50)),
                ('Fax', models.CharField(max_length=50)),
                ('HomePage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('QuantityPerUnit', models.CharField(max_length=255)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UnitsInStock', models.IntegerField()),
                ('UnitsOnOrder', models.IntegerField()),
                ('ReorderLevel', models.IntegerField()),
                ('Discontinued', models.BooleanField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.suppliers')),
            ],
        ),
    ]
