# Generated by Django 6.0.4 on 2026-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_categories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='OldPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
